// Generated by Apple Swift version 1.2 (swiftlang-602.0.53.1 clang-602.0.53)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface NSObject (SWIFT_EXTENSION(PKLormappingSwift))
@end


SWIFT_CLASS("_TtC17PKLormappingSwift7PKArray")
@interface PKArray : NSObject
@property (nonatomic, copy) NSDictionary * __nullable foreginKeyMapping;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithEntityNSObject:(NSObject * __nonnull)entityNSObject OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17PKLormappingSwift16PKDataBaseAccess")
@interface PKDataBaseAccess : NSObject
@property (nonatomic) NSInteger timeOut;
@property (nonatomic) NSInteger poolCount;
@property (nonatomic) BOOL isCacheData;
+ (PKDataBaseAccess * __nonnull)shareAccess:(NSString * __nonnull)path;
- (void)closeDataBase;
@end

@class NSDate;

SWIFT_CLASS("_TtC17PKLormappingSwift10PKDateUnit")
@interface PKDateUnit : NSObject
+ (NSString * __nonnull)dateFormatterStringWithDate:(NSDate * __nonnull)date formatter:(NSString * __nonnull)formatter;
+ (NSString * __nonnull)nowDate;
+ (NSDate * __nonnull)stringFormatterDateWithDateStr:(NSString * __nonnull)dateStr formatter:(NSString * __nonnull)formatter;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PKQueryPage;

SWIFT_CLASS("_TtC17PKLormappingSwift7PKHQLer")
@interface PKHQLer : NSObject
@property (nonatomic) PKQueryPage * __nullable queryPage;
- (NSString * __nonnull)getHQL;
- (PKHQLer * __nonnull)addEqual:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addNotEqual:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addLike:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addNotLike:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addStartLike:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addEndLike:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addIn:(NSString * __nullable)key value:(NSArray * __nullable)value;
- (PKHQLer * __nonnull)addNotIn:(NSString * __nullable)key value:(NSArray * __nullable)value;
- (PKHQLer * __nonnull)addIsNull:(NSString * __nullable)key;
- (PKHQLer * __nonnull)addNotNull:(NSString * __nullable)key;
- (PKHQLer * __nonnull)addLessThan:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addLessEqualThan:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addGreatThan:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addGreatEqualThan:(NSString * __nullable)key value:(id __nullable)value;
- (PKHQLer * __nonnull)addBetweenDate:(NSString * __nullable)key startDate:(NSString * __nullable)startDate endDate:(NSString * __nullable)endDate;
- (PKHQLer * __nonnull)addEqualDate:(NSString * __nullable)key date:(NSString * __nullable)date;
- (PKHQLer * __nonnull)addLessDate:(NSString * __nullable)key date:(NSString * __nullable)date;
- (PKHQLer * __nonnull)addLessEqualDate:(NSString * __nullable)key date:(NSString * __nullable)date;
- (PKHQLer * __nonnull)addGreatDate:(NSString * __nullable)key date:(NSString * __nullable)date;
- (PKHQLer * __nonnull)addGreatEqualDate:(NSString * __nullable)key date:(NSString * __nullable)date;
- (PKHQLer * __nonnull)addOr:(PKHQLer * __nullable)hql;
- (PKHQLer * __nonnull)addAllOr:(PKHQLer * __nullable)hql;
- (PKHQLer * __nonnull)addOrderBy:(NSString * __nullable)key type:(NSString * __nullable)type;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17PKLormappingSwift11PKQueryPage")
@interface PKQueryPage : NSObject
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithRows:(NSInteger)rows page:(NSInteger)page OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
